build:
  image: node:18-alpine
  stage: build
  script:
    - npm ci
    - npx ng build
  artifacts:
    paths:
      - dist/
    expire_in: 24 hours
  cache:
    key: build
    paths:
      - $HOME/.npm/

deploy:
  stage: deploy
  image: node:18-alpine
  only:
    - master
  dependencies:
    - build
  script:
    - npm ci
    - GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS" npx ng deploy

stages:
  - build
  - deploy
